### ISSUE TITLE
Ability to set custom bucket_cutoffs

### ISSUE THREAD

**Issue by danishpruthi** [neulab/compare-mt#22]
I am not sure if there is an explicit way of setting for custom `bucket_cutoffs`. Right now the optional arguments are taken as a string, which is further split by a comma, so if I wish to specify a list of cutoffs, it will also be split by comma, and wouldn't work.

**Comment by neubig** [comment]
There probably isn't. You could potentially separate the values with another character like a colon?

This overloading of special characters becomes a difficulty when specifying things by command-line arguments, but I think doing something like using configuration files instead of command line arguments would probably hurt the usability of the tool. Not sure if there's a good all-around solution?
